version: '1.{build}'

branches:
  only:
    - master

skip_tags: true

clone_folder: c:\gopath\src\github.com\mogaika\god_of_war_browser

environment:
  GOPATH: c:\gopath
  GOARCH: 386
  GOOS: windows

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go test -v ./...
  - go build

after_build:
  - 7z a god_of_war_browser.zip -r c:\gopath\src\github.com\mogaika\god_of_war_browser\web -x!*.go
  - 7z a god_of_war_browser.zip god_of_war_browser.exe

test: off

deploy: off

artifacts:
  - path: god_of_war_browser.zip
    name: god_of_war_browser
